name: Events Processing Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 * * * *'  # once every hour at the 30-minute mark
  workflow_dispatch:

jobs:
  process-events:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Setup environment variables
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env

      - name: Run events processing script
        run: poetry run python -m newsletter.process.events