name: Newsletter Processing and Distribution Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * 0'  # Once every week on Sunday at 1am UTC
  workflow_dispatch:

jobs:
  process-and-distribute-newsletter:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      BROADCAST_MODE: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Setup environment variables
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> .env
          echo "BROADCAST_MODE=true" >> .env

      - name: Run newsletter processing script
        run: poetry run python -m newsletter.process.newsletter

      - name: Broadcast newsletter to Telegram subscribers
        run: poetry run python -m newsletter.process.telegram

      - name: Log completion
        run: echo "Newsletter processing and distribution completed at $(date)"