name: Newsletter Pipeline

on:
  # 1) Create a dev newsletter on push to main
  push:
    branches: [ 'main' ]

  # 2) Create a production newsletter at Saturday 7 AM UTC
  schedule:
    - cron: '0 7 * * 6'

  # 3) Manual run
  workflow_dispatch:

jobs:
  create-newsletter:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # We'll dynamically set IS_DEV below depending on the event
      IS_DEV: "false"


    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Determine environment (dev vs. production)
        id: check-env
        run: |
          # Default to nothing
          echo "IS_DEV=" >> $GITHUB_ENV

          # If we pushed to main => dev newsletter
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "IS_DEV=true" >> $GITHUB_ENV
            echo "Dev newsletter creation."
          # If it's schedule => production newsletter
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            CURRENT_HOUR=$(date -u +"%H")
            CURRENT_DAY_OF_WEEK=$(date -u +"%u")
            # Saturday at 7 AM => production
            if [ "$CURRENT_DAY_OF_WEEK" = "6" ] && [ "$CURRENT_HOUR" = "07" ]; then
              echo "IS_DEV=false" >> $GITHUB_ENV
              echo "Production newsletter creation."
            else
              echo "No newsletter creation needed at this time."
            fi
          else
            echo "No newsletter creation needed."
          fi

      - name: Create newsletter (only if IS_DEV is set)
        if: env.IS_DEV != ''
        run: |
          echo "Creating newsletter with IS_DEV=${IS_DEV}"
          poetry run python -m newsletter.process.newsletter

      - name: Log completion
        run: echo "Finished at $(date)"
